apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - allow-dns.yaml
  - allow-product-api.yaml
  - allow-storefront.yaml
  - allow-order-worker.yaml

commonLabels:
  app.kubernetes.io/part-of: cloudnative-commerce
  app.kubernetes.io/managed-by: kustomize
