apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/storefront

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: storefront
        namespace: commerce
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              app.kubernetes.io/version: dev
          spec:
            containers:
              - name: storefront
                image: storefront:dev

  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: storefront
        namespace: commerce
      spec:
        minReplicas: 1
        maxReplicas: 2

  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: storefront
        namespace: commerce
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::911788523496:role/cloudnative-commerce-dev-storefront-irsa

  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: storefront-config
        namespace: commerce
      data:
        NODE_ENV: "development"
        NEXT_PUBLIC_API_URL: "http://product-api.commerce.svc.cluster.local"
