apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-labels.yaml
  - restrict-registries.yaml
  - require-resource-limits.yaml
  - disallow-privileged.yaml

commonLabels:
  app.kubernetes.io/part-of: cloudnative-commerce
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: policy
