apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# values.yaml is used with `helm install -f values.yaml`, not kustomize.
# CRD resources are applied via kustomize after ESO is running.
resources:
  - clustersecretstore.yaml
  - externalsecret-product-api.yaml
  - externalsecret-order-worker.yaml

commonLabels:
  app.kubernetes.io/part-of: cloudnative-commerce
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: secrets
