# Remote backend configuration — stores Terraform state in S3 with DynamoDB locking.
#
# WHY REMOTE STATE?
# - Local state is lost if your machine dies or you switch workstations
# - S3 provides versioning so you can roll back to a previous state snapshot
# - DynamoDB locking prevents two engineers from running `apply` simultaneously,
#   which would corrupt state and potentially create duplicate resources
#
# IMPORTANT: The S3 bucket and DynamoDB table must be created BEFORE running
# `terraform init` in this directory. Use the bootstrap script:
#   make bootstrap-backend
# or run manually (see docs/runbooks/terraform-backend-bootstrap.md)

terraform {
  backend "s3" {
    # State bucket — one bucket per AWS account, one prefix per environment.
    # Bucket name must be globally unique; using account ID ensures uniqueness.
    bucket = "cloudnative-commerce-tfstate-911788523496"
    key    = "environments/dev/terraform.tfstate"
    region = "ap-south-1"

    # Server-side encryption — state files contain sensitive data (passwords,
    # private keys generated by Terraform). AES256 is sufficient for most
    # compliance requirements; use aws:kms if you need audit trails.
    encrypt = true

    # DynamoDB table for state locking and consistency checking.
    # Table must have a primary key named "LockID" (string type).
    dynamodb_table = "cloudnative-commerce-tfstate-lock"

    # S3 versioning is enabled on the bucket (see bootstrap script).
    # This allows `aws s3api list-object-versions` to recover from bad applies.
  }
}
